apiVersion: projectcalico.org/v3
kind: StagedGlobalNetworkPolicy
metadata:
  name: nigel-security.block-tor
spec:
  tier: nigel-security
  order: 210
  namespaceSelector: 'kubernetes.io/metadata.name == "capital-one"'
  serviceAccountSelector: ''
  egress:
    - action: Deny
      source: {}
      destination:
        selector: feed == ejr-vpn
  doNotTrack: false
  applyOnForward: false
  preDNAT: false
  types:
    - Egress
