apiVersion: projectcalico.org/v3
kind: StagedGlobalNetworkPolicy
metadata:
  name: nigel-security.block-feodo
spec:
  tier: nigel-security
  order: 210
  selector: projectcalico.org/namespace = "capital-one"
  namespaceSelector: ''
  serviceAccountSelector: ''
  egress:
    - action: Deny
      source: {}
      destination:
        selector: role == "aws-metadata-ip"
  doNotTrack: false
  applyOnForward: false
  preDNAT: false
  types:
    - Egress
